version: "3.8"
services:
    db:
      image: postgres:alpine
      container_name: website-uptime
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=uptime
      ports:
        - 5430:5432
      volumes:
        - postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  postgres-data:
    external: false
