# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: testyash
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: uptime-checker
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
service: checking-service

stages:
  prod:
    # Enables observability in the prod stage
    observability: false

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:  
  logger:
    handler: src/uptime.handler


